---
title: "じょし 1"
author: "植北　ひとし"
date: "20 de novembro de 2018"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    include:
      in_header: header.html
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## じょし 1

### Legenda

a. <div class="alert alert-primary" role="alert">Pergunta</div>

b. <div class="alert alert-info" role="alert">Tradução</div>

c. <div class="alert alert-warning" role="alert">Explicação da resposta</div>

d. <div class="alert alert-dark" role="alert">Dúvida</div>

### Respostas

1. 
<div><div class="alert alert-primary" role="alert">
わたしは　あたらしい　じてんしゃ（が）　ほしいです。  
へ　　に　　が　　で  
</div><div class="alert alert-info" role="alert">
Eu quero/desejo uma bicicleta nova.  
</div><div class="alert alert-warning" role="alert">
As frases com ほしいです são com a partícula `が`.  
N`が`　ほしいです  
Try - Página 40 - Item 10
</div></div>

2. 
<div><div class="alert alert-primary" role="alert">
えいがは　なんじ　（に）　おわりますか。  
くらい　　　から　　　まで　　　に  
</div></div>

3. 
<div><div class="alert alert-primary" role="alert">
きのう　おとうとは　びょうき（で）　学校を　やすみました。  
が　　　に　　　で　　　と  
</div><div class="alert alert-info" role="alert">
Ontem minha irmã mais nova estava doente então não foi para a escola.  
</div><div class="alert alert-warning" role="alert">
A estrutura da frase é:  
`Motivo`で + Verbo  
</div></div>

4. 
<div><div class="alert alert-primary" role="alert">
わたしは　<ruby>先<rt>せん</rt>生<rt>せい</rt></ruby>（と）　３０ぷん　はなしました。  
と　　　を　　　へ　　　の  
</div><div class="alert alert-info" role="alert">
Conversei com a professa por 30 minutos.  
</div></div>

5. 
<div><div class="alert alert-primary" role="alert">
だれ（か）　てつだってください。  
に　　　か　　　を　　　が  
</div><div class="alert alert-info" role="alert">
Por favor, ajude alguém.    
</div><div class="alert alert-warning" role="alert">
<ruby>手<rt>て</rt>伝<rt>つだ</rt>い</ruby> = Ajudar  
(Pronome Interrogativo)か + V-`て` ou V-`で` + ください  
</div></div>

6. 
<div><div class="alert alert-primary" role="alert">
マリオさんは　テニスは　しますが　サッカー（は）　しません。  
は　　と　　が　　も  
</div><div class="alert alert-info" role="alert">
O senhor Mário joga tenis, mas não joga futebol.  
</div><div class="alert alert-warning" role="alert">
O `が` possui significado de `mas` e une duas orações (cada qual com o seu tópico principal).  
</div></div>

7. 
<div><div class="alert alert-primary" role="alert">
<ruby>花<rt>はな</rt></ruby>の　しゃしんを　10まい　（ぐらい）　とりました。  
が　　　を　　　など　　　ぐらい  
</div><div class="alert alert-info" role="alert">
Tirei mais ou menos 10 fotos de flores.  
</div></div>

8. 
<div><div class="alert alert-primary" role="alert">
日曜日に　そうじ（や）　せんたくを します。  
を　　　や　　　も　　　で  
</div><div class="alert alert-info" role="alert">
No domingo farei limpeza e lavarei roupa.  
</div><div class="alert alert-warning" role="alert">
Vocabulário: せんたく = Lavar roupa.  
`N1`や`N2`  
O uso do `や` é para mostrar alguns itens que serão feitos (somente os mais relevantes) e normalmente é usado com o `など` (que é o nosso etc.). Já o `と` enumera todos os itens.
</div></div>

9. 
<div><div class="alert alert-primary" role="alert">
パーティーは　いつ（が）　いいですか。  
が　　　に　　　を　　　と  
</div><div class="alert alert-info" role="alert">
Quando tem uma festa boa?
</div><div class="alert alert-warning" role="alert">
`Pronome Interrogativo`が + いいですか
</div></div>

10. 
<div><div class="alert alert-primary" role="alert">
えきの　ちかく（の）　みぜで　この<ruby>本<rt>ほん</rt></ruby>を　かいました。  
で　　　に　　　を　　　の  
</div><div class="alert alert-info" role="alert">
Comprei esse livro na loja perto da estação.  
</div></div> 

11. 
<div><div class="alert alert-primary" role="alert">
一人　（だけ）　<ruby>早<rt>はや</rt></ruby>く　かえりました。  
</div><div class="alert alert-info" role="alert">
Somente/apenas uma pessoa voltou cedo.  
しか　　　だけ　　　から　　　まで  
</div></div>

12. 
<div><div class="alert alert-primary" role="alert">
あそこで　とり（が）　ないていますよ。  
を　　　に　　　が　　　の  
</div><div class="alert alert-info" role="alert">
Ali os pássaros cantam.  
</div><div class="alert alert-warning" role="alert">
Vocabulário: ないています = cantar do passarinho
</div></div>

13. 
<div><div class="alert alert-primary" role="alert">
この　りょうりは　ぎゅうにく（か）　ぶたにくを　つかいます。  
が　　　か　　　　も　　　で  
</div><div class="alert alert-info" role="alert">
Este prato usa carne bovina ou suína.
</div><div class="alert alert-warning" role="alert">
Neste caso `か` tem o significado de `ou`.
Substantivo + `か` + Substantivo
</div></div>

14. 
<div><div class="alert alert-primary" role="alert">
この　りょうりは　ぎゅうにくも　ぶたにく　（も）　つかいません。  
が　　　か　　　も　　　で  
</div><div class="alert alert-info" role="alert">
Este prato não usa carne bovina e nem a carne suína. 
</div><div class="alert alert-warning" role="alert">
A construção dessa frase segue a estrutura `nem isso` e `nem aquilo`.  
Substantivo + `も` + Substantivo `も`  
ぎゅうにく`も` ぶたにく`も`  
</div></div>


15. 
<div><div class="alert alert-primary" role="alert">
カルロスくん（の）　来る日は　土曜日。  
を　　　へ　　　で　　　の  
</div><div class="alert alert-info" role="alert">
O garoto Carlos 
</div><div class="alert alert-warning" role="alert">
Vocabulário = 来る日 = próximos dias (??? Confirmar)
</div><div class="alert alert-dark" role="alert">
Fiz por exclusão. Preciso de uma resposta mais elaborada!!
</div></div>

16. 
<div><div class="alert alert-primary" role="alert">
カルロスくん（が）　来る日は　土曜日。  
を　　　へ　　　で　　　が  
</div><div class="alert alert-dark" role="alert">
Fiz por exclusão. Preciso de uma resposta mais elaborada!!
</div></div>

17. 
<div><div class="alert alert-primary" role="alert">
あの　けいたいは　だれ（の）　ですか。  
を　　　へ　　　で　　　の  
</div><div class="alert alert-info" role="alert">
Aquele celular de quem é?  
</div><div class="alert alert-warning" role="alert">
Neste caso `の` dá o sentido de posse ao pronome interrogativo  `だれ`.
</div></div>

18. 
<div><div class="alert alert-primary" role="alert">
じゅぎょうは　なんじ（から）　ですか。  
ぐらい　　　から　　まで　　　に  
</div><div class="alert alert-info" role="alert">
A aula é a partir de que horas?  
A aula é até que horas?  
</div><div class="alert alert-warning" role="alert">
Há duas respostas: `から` e `まで`.
</div></div>


19. 
<div><div class="alert alert-primary" role="alert">
おなかが　すきましたね。　なに（か）　<ruby>食<rt>た</rt></ruby>べませんか。  
が　　　か　　　も　　　で  
</div><div class="alert alert-info" role="alert">
Estou com fome. Quer comer alguma coisa?
</div><div class="alert alert-warning" role="alert">
Quando não se tem certeza sobre a resposta da outra parte (você está sugerindo), usa-se essa construção.
</div></div>

20. 
<div><div class="alert alert-primary" role="alert">
ホットドッグと　ハンバーガーと　どちら（が）　いいですか。  
へ　　　に　　　が　　　で  
</div><div class="alert alert-info" role="alert">
Hot-dog ou hamburguer qual você prefere?  
</div><div class="alert alert-warning" role="alert">
A construção desta frase é rígida e sempre terá a mesma forma.  
Substantivo + `と` + Substantivo + `と` + どちら`が`　`いいですか`。  
Sempre será usado o `が`.
</div></div>

21. 
<div><div class="alert alert-primary" role="alert">
あした　バス（で）　サンパウロへ　いきます。  
を　　　へ　　　で　　　に  
</div><div class="alert alert-info" role="alert">
Amanhã irei de ônibus para São Paulo.  
</div><div class="alert alert-warning" role="alert">
Deve-se assinalar o `で` pois exprime o meio de locomoção.  
</div></div>

22. 
<div><div class="alert alert-primary" role="alert">
<ruby>早<rt>はや</rt></ruby>く　バス（に）　のって　ください。  
を　　　へ　　　で　　　に  
</div><div class="alert alert-info" role="alert">
Entre rápido no ônibus.  
</div><div class="alert alert-warning" role="alert">
Lembre-se que のります e はいります exigem o `に`.  
</div></div>

23. 
<div><div class="alert alert-primary" role="alert">
わたしは　まいあさ　８じ（ごろ）　おきます。  
とき　　　ごろ　　　など　　　ぐらい  
</div><div class="alert alert-info" role="alert">
Eu acordo por volta das 8 horas.  
</div><div class="alert alert-dark" role="alert">
Preciso recordar!!
</div></div>

24. 
<div><div class="alert alert-primary" role="alert">
わたしは　まいあさ　８じかん　（ぐらい）　ねます。  
とき　　　ごろ　　　など　　　ぐらい  
</div><div class="alert alert-info" role="alert">
Eu acordo aproximadamente às 8 horas
</div><div class="alert alert-dark" role="alert">
Preciso recordar!!
</div></div>

25. 
<div><div class="alert alert-primary" role="alert">
あした　いっしょに　ショッピングセンター（へ）　いきませんか。  
へ　　　で　　　と　　　を  
</div><div class="alert alert-info" role="alert">
Amanhã vamos juntos ao Shopping Center?  
</div></div>  